# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
