# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161030_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='concreteuser',
            name='token',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
    ]
