# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_concreteuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concreteuser',
            name='token',
            field=models.CharField(blank=True, default='', max_length=36, null=True, unique=True),
        ),
    ]
